#!/data/data/com.termux/files/usr/bin/bash
echo 安装JDK17和VNC服务器...
pkg up -y && pkg i x11-repo -y && pkg i tigervnc -y && pkg i openjdk-17 -y
echo 下载jsql-injection...
wget https://ghproxy.com/github.com/ron190/jsql-injection/releases/download/v0.85/jsql-injection-v0.85.jar
echo 设置DISPLAY变量和启动VNC服务器...
export DISPLAY=:1
vncserver :1
echo 启动JSQL-INJECTION...
java -jar jsql-injection-v0.85.jar | echo 打开VNC Viewer，IP：   :1
